import { existsSync, readdirSync } from 'node:fs'
import { basename, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'

// This file is copied into the gh-pages branch as docs/.vitepress/config.mts
// by .github/workflows/docs.yml. Edit it here, never there.

const docsRoot = fileURLToPath(new URL('..', import.meta.url))
const apiRoot = resolve(docsRoot, 'api')

// The API pages are generated by tools/docgen.lua, so the sidebar is built by
// reading the directory instead of listing every module by hand. A new module
// appears in the navigation as soon as it exists in src/.
function apiItems(folder: string) {
  const directory = resolve(apiRoot, folder)
  if (!existsSync(directory)) return []

  return readdirSync(directory)
    .filter((file) => file.endsWith('.md'))
    .sort((left, right) => left.localeCompare(right))
    .map((file) => ({
      text: basename(file, '.md'),
      link: `/api/${folder}/${basename(file, '.md')}`,
    }))
}

export default defineConfig({
  title: 'Obsidian',
  description: 'Obsidian API documentation for CC:Tweaked',
  lang: 'en-US',
  // GitHub project site: https://pyroxenium.github.io/Obsidian/
  // Change this if the site ever moves to a custom domain.
  base: '/Obsidian/',
  lastUpdated: true,

  themeConfig: {
    siteTitle: 'Obsidian',
    search: {
      provider: 'local',
    },
    nav: [
      { text: 'Home', link: '/home' },
      { text: 'Guides', link: '/guides/engine_quickstart' },
      { text: 'API Reference', link: '/api/' },
    ],
    sidebar: {
      '/guides/': [
        {
          text: 'Guides',
          items: [
            { text: 'Engine Quickstart', link: '/guides/engine_quickstart' },
            { text: 'ECS Guide', link: '/guides/ecs_guide' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'API Reference',
          link: '/api/',
        },
        {
          text: 'Runtime',
          items: [{ text: 'engine', link: '/api/engine' }],
        },
        {
          text: 'Core',
          collapsed: false,
          items: apiItems('core'),
        },
        {
          text: 'UI',
          collapsed: false,
          items: apiItems('core/ui'),
        },
        {
          text: 'Formats',
          items: [{ text: 'flimg', link: '/api/flimg' }],
        },
      ],
    },
    outline: [2, 3],
    docFooter: {
      prev: false,
      next: false,
    },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 Pyroxenium',
    },
    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/Pyroxenium/Obsidian',
      },
    ],
  },
})
